# You must put this in your repo master branch  as repo/.github/workflow/gitbook_action.yml
# You must add the following secrets in your Secrets(repo->Setting->Secrets->Add a new secret)  
# Name:   GIT_NAME              Value:  your git name like ZanderZhao
# Name:   GIT_EMAIL             Value:  your git email like example@exp.com
# Name:   THE_GITHUB_TOKEN      Value:  you can git it from Settings->Developer settings->Personal access tokens->Generate new token
# Name:   THE_GITHUB_REF        Value:  github.com/your_name/your_repo_name.git
# Name:   RES_FOR_PAGES         Value:  put the branch name here like gh-pages,where the build book you want put for
# Pay attention，THE_GITHUB_REF can't add https:// before, 
# And RES_FOR_PAGES must be create and be set as pages before.
# When you make THE_GITHUB_TOKEN ,the push permission is must have，the others, you can add.
# You can visit https://zlogs.net/gitbook-action/ for more information.

name: 'Gitbook Action'

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install_gitbook_plugins
      run: |
        npm install gitbook-cli  -g
        gitbook -v
        gitbook install
    - name: build_gitbook
      run: |
        gitbook build
    - name: push_to_pages
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REF: github.com/${{github.repository}}    
      run: |
        cd ./_book
        git config --global user.name "caoxiaodao"
        git config --global user.email "18515878076@163.com"
        git init
        git remote add origin https://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@github.com/caoxiaodao/note.git
        git add . 
        git commit -m "Updated"
        git branch -M master
        git remote set-url origin git@github.com:caoxiaodao/note.git
        git push --force --quiet "https://<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>@github.com/caoxiaodao/note.git" master:gh-pages
        CI: true
